version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: smartchat:latest
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - MONGODB_URL=${MONGODB_URL}
      - SECRET_KEY=${SECRET_KEY}
      - MONGODB_DB=${MONGODB_DB:-smartchat}
      - PORT=${PORT:-8000}
      - WEB_CONCURRENCY=${WEB_CONCURRENCY:-4}
      - PYTHONUNBUFFERED=1
      - TZ=UTC
      - REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
      - CURL_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
      - SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
      # - OPENAI_API_KEY=${OPENAI_API_KEY}
    dns:
      - 8.8.8.8
      - 8.8.4.4
    networks:
      app-network:
        aliases:
          - smartchat-app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 1G
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

networks:
  app-network:
    name: smartchat-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16